### ISSUE TITLE
Using `register()` correctly

### ISSUE THREAD

**Issue by odow** [kirui93/ScenTrees.jl#1]
Just an FYI, that you don't need to register every commit.

Registering is only needed if you want to release new code features so that they are available with `] up ScenTrees`. 

In addition, you need to increment the version in `Project.toml`. https://github.com/kirui93/ScenTrees.jl/blob/595c30e6f58711b41448d87c0845f7f034803025/Project.toml#L4

Here's an example doing it in GLPK:
https://github.com/JuliaOpt/GLPK.jl/commit/999503e430b0263f341c68aec2297fa4159086cb

You may want to read: https://github.com/JuliaRegistries/Registrator.jl

**Comment by kirui93** [comment]
Wow , thank you. I had not realized about that.
I have one question, what happens when you make a release of the package on GitHub?

**Comment by odow** [comment]
For the short-term, you probably don't need to worry about making a release. If you make a release, it just means that people can install using the Julia package manager (i.e., using `] add ScenTrees`). So I would wait until you have the package in a nearly finished state.

In the mean time, people can install the latest version using `] add https://github.com/kirui93/ScenTrees.jl`. This is what I use for SDDP.jl, for example.

**Comment by kirui93** [comment]
Probably then I need to increment the version now manually and then I continue working on the updates.
Thank you Oscar

**Comment by kirui93** [comment]
Thank you for your helpful comment Oscar. I will close this issue for now.
