### ISSUE TITLE
[JOSS] Consider AbstractTrees

### ISSUE THREAD

**Issue by matbesancon** [kirui93/ScenTrees.jl#10]
[AbstractTrees.jl](https://github.com/Keno/AbstractTrees.jl/) could make the development of this package much smoother

**Comment by matbesancon** [comment]
It would remove some bits from the package here about tree management

**Comment by matbesancon** [comment]
Linking to the review: https://github.com/openjournals/joss-reviews/issues/1912

**Comment by matbesancon** [comment]
Just to note, this part is not mandatory and simple advice to make the package easier to maintain (less code)

**Comment by kirui93** [comment]
I will though seems the package is no longer maintained as it hasn't been update for a while. 
Referring to this [issue](https://github.com/Keno/AbstractTrees.jl/issues/39)

**Comment by kirui93** [comment]
In this case, we are still waiting for the author of this package to provide the documentation at least to enable us understand how we can incorporate its utilities. For now, we think it is not necessary but if we find a common ground, then we will.
