### ISSUE TITLE
[JOSS] Improvements for software paper

### ISSUE THREAD

**Issue by juliohm** [kirui93/ScenTrees.jl#13]
Below you can find some review comments on the software paper:

# Introduction

## Paragraph 1

>In multistage stochastic optimization we are interested in decision making under uncertainty.

It is the opposite direction: decision making under uncertainty leads to multistage optimization sometimes. Please adjust the text to reflect this direction.

>In this setting, stochastic processes have random and uncertain outcomes and decisions must be made at different stages of the process.

It is not only in this setting, it is in general. Stochastic processes have random outcomes always. You could also eliminate the word uncertain since you are already using random.

>It is generally intractable to solve mathematical programs with uncertain parameters described by an underlying probability distribution.

This statement is too general. Many mathematical programs with uncertain parameters are tractable. You need to adjust the sentence to make it more smooth.

>The common approach is to form an approximation of the original stochastic process or underlying distribution by discretization.

Common approach to what exactly? Please review this first paragraph as it is the most important of all paragraphs here. You need to show the usefulness of your package, and for that you need to understand very well the problem it is addressing, nothing more, nothing less.

>The procedure of discretizing a stochastic process is called scenario tree generation. We depict the possible sequences of data for this processes in form of a scenario tree in the case of a discrete time stochastic process and a scenario lattice for Markov processes.

This is the first sentence of the first paragraph that is simple to read, and to the point. Please review the entire paragraph based on the comments above to better set the ground for your package.

## Paragraph 2

>Since the paper of @Hoyland2001, scenario tree generation has been used to solve various multistage stochastic problems in the industry and academia. Various authors including @Pflug2001, @KovacevicPichler and @PflugPichler2016 have come up to add and improve various ideas into the process of generating scenario trees.

You need a connector here. When you write "Since...", you need to have a coma somewhere with the other sentence. In this case, you need ", various authors...". I would simply write: "various authors including ... did come up with various ideas for generating scenario trees."

>However, there is no fast and open-source implementation of the algorithm that has been available in the public domain for various users to appreciate. Instead, various 

I would rewrite it as "Still, an open-source implementation is missing, and researchers are forced to code their own versions..." Also, it is fine if people choose other languages, you shouldn't imply in the text that using different languages is bad.

The rest of the paragraph can be removed. It is redundant and the message was already conveyed with the previous sentence.

## Paragraph 3

I would start the introduction here. Maybe just remove the previous paragraphs entirely? This paragraph and the remaining ones in the introduction are clear, to the point, and people in the area will quickly get it. With the previous paragraphs you risk loosing the reader.

# Main features of the package

## Paragraph 1

>The stochastic approximation framework allows ScenTrees.jl to be generally applicable to any stochastic process to be approximated.

Rewrite it to "ScenTrees.jl is applicable to any type of stochastic process."

>The following are key features that ScenTrees.jl provides. Implementation details and examples of usage can be found in the software's documentation.^[Documentation: https://kirui93.github.io/ScenTrees.jl/latest]

Rewrite it to "The key features of the package are:" Also move the implementation details and examples of usage to after the bullet points. They are breaking the flow of thought.

# Example

The subsection should be called "Approximation with scenario tree".

Overall, I suggest you to use a English corrector online to fix the errors, and to organize the thoughts better. This can help improve the experience of readers by a lot. Hope you can address the comments above, the software paper needs some extra work.

**Comment by kirui93** [comment]
Thank you so much for the important comments.
I am already looking on it

**Comment by kirui93** [comment]
@juliohm thank you for your insightful comments. It has helped me improve the paper up to the current state.

**Comment by matbesancon** [comment]
Linking to the review: https://github.com/openjournals/joss-reviews/issues/1912

**Comment by kirui93** [comment]
@matbesancon @juliohm Thank you for the important and insightful comments about the software paper. I will appreciate if you mention any other issue that you think is necessary. But, we think that the current state of the paper explains to our goal.

**Comment by kirui93** [comment]
@juliohm @matbesancon I would like to edit the introduction of the software paper. I have a short and to the point version of it but I don know if it is a good idea to change it now as am sure you are already reviewing it.

**Comment by matbesancon** [comment]
It's ok on my side if you edit the manuscript, don't forget to recompile so
that we get the last version

**Comment by kirui93** [comment]
Okay. I hope it is also okay for @juliohm.

**Comment by juliohm** [comment]
Please go ahead. +1

**Comment by kirui93** [comment]
@juliohm @matbesancon Thank you so much for your replies as well as your patience and also for the important reviews. I will update recompile immediately in the joss issue for you to get this version.

**Comment by kirui93** [comment]
@juliohm @matbesancon It is now very ready.

**Comment by juliohm** [comment]
Thank you @kirui93 for the update. The new draft of the paper looks much better. I am marking the issue as solved.
