### ISSUE TITLE
Issue with lattice approximation

### ISSUE THREAD

**Issue by rachaelalfant** [kirui93/ScenTrees.jl#19]
Hello, 

I'm attempting to follow the tutorial for scenario lattices, and am receiving an error after typing in the following command: 
```
ExampleLattice = lattice_approximation([1,2,3,4,5],gaussian_path1D,1000000,2,1);
```
![Screenshot from 2022-08-05 17-28-54](https://user-images.githubusercontent.com/55371799/183219503-07d6adb0-800c-4a09-a150-c3f44d96826d.png)

I obtained the command from this link: https://kirui93.github.io/ScenTrees.jl/stable/tutorial/tutorial3/. Am I doing something wrong? Any help would be greatly appreciated.

**Comment by kirui93** [comment]
Hello @rachaelalfant ,

Thanks for pointing this out. There is a typo in the example. The function gaussian_path1D() returns a 4x1 matrix. Hence, we should give a vector of 4 dimension, i.e., bstructure = [1,2,3,4]. 

![image](https://user-images.githubusercontent.com/36660022/183241993-ea9e64ff-460f-4375-8dae-4939ae95625e.png)

Will update with another function for length 5. 

Additionally, you can write your own function that generates a vector with any dimension.

Thank you.

**Comment by rachaelalfant** [comment]
Thank you for your help!
