### ISSUE TITLE
[JOSS] General comments about the documentation

### ISSUE THREAD

**Issue by juliohm** [kirui93/ScenTrees.jl#7]
The documentation is overall very didactic. However, a few sections are not very useful in my opinion:

1. The Usage section showing a snapshot of ScenTrees.jl: https://kirui93.github.io/ScenTrees.jl/latest/tutorial/tutorial1/#Usage-1
2. The Performance of ScenTrees.jl header section discussing the Julia language: https://kirui93.github.io/ScenTrees.jl/latest/tutorial/tutorial5/#Performance-of-ScenTrees.jl-1

I would delete these sections as they do not convey an information that is important for users of the package. As users we already know that Julia is awesome, and we already know that the top package ScenTrees.jl contains the exports. I would eliminate the section on the Julia Language and maybe rewrite the Usage section to provide useful information. Maybe it is not needed given the number of tutorials you already provide in the documentation.

These are just general comments to improve the experience reading the docs. Please let me know if you would like to change these or leave as it is. I am not forcing anything here, just suggesting :)

**Comment by juliohm** [comment]
As another general comment, you seem to use the term `library` in some places of the docs like it was been used in the README. I suggest renaming all occurrences of library to package to follow Julia conventions. It is a minor detail but can help create a clean ecosystem.

**Comment by kirui93** [comment]
> The documentation is overall very didactic. However, a few sections are not very useful in my opinion:
> 
> 1. The Usage section showing a snapshot of ScenTrees.jl: https://kirui93.github.io/ScenTrees.jl/latest/tutorial/tutorial1/#Usage-1
> 2. The Performance of ScenTrees.jl header section discussing the Julia language: https://kirui93.github.io/ScenTrees.jl/latest/tutorial/tutorial5/#Performance-of-ScenTrees.jl-1
> 
> I would delete these sections as they do not convey an information that is important for users of the package. As users we already know that Julia is awesome, and we already know that the top package ScenTrees.jl contains the exports. I would eliminate the section on the Julia Language and maybe rewrite the Usage section to provide useful information. Maybe it is not needed given the number of tutorials you already provide in the documentation.
> 
> These are just general comments to improve the experience reading the docs. Please let me know if you would like to change these or leave as it is. I am not forcing anything here, just suggesting :)




Thank you @juliohm for the useful suggestions. 
At the moment, I would like to keep those sections.
For Performance, one of our motives for creating ScenTrees.jl was for speed. Many algorithms that we have worked with is in MATLAB and they seemed  to be slow and hence with julia speed, we were able to improve and also reduce the runtime speed of generating any particular scenario tree and scenario lattice.
For the Usage, I will still revisit that part to be more clear and informative as it was intended.

**Comment by kirui93** [comment]
> As another general comment, you seem to use the term `library` in some places of the docs like it was been used in the README. I suggest renaming all occurrences of library to package to follow Julia conventions. It is a minor detail but can help create a clean ecosystem.

Yeah, that's true. I have just realized that. I will do this tonight.

**Comment by juliohm** [comment]
Sounds good. Just to clarify that my comment about the performance section was the very top of that page, not the great tables and plots you present. These are actually very nice to have.

My comment was about those paragraphs discussing Julia and multiple-dispatch. For Julia users, this section is kind of a waste of time. We spend time reading it to discover that there is nothing specific about ScenTrees.jl there. I would be curious about possible performance implementations in the package, and other tricks you used, not the actual language. Anyways, feel free to leave it as is. :)

**Comment by kirui93** [comment]
Okay. I am sorry I didn't get you at first. I will also have a look on that.
Thank you so much.

**Comment by kirui93** [comment]
@juliohm Thank you so much for the important notes you gave me.
I have already implemented most of them apart PyPlot and Reexport which I will look on it later.

**Comment by matbesancon** [comment]
Follow-up on the documentation, the docstring of an identifier needs to be on the line just before this identifier:
OK:
```
"""
    f

Implement the f function on these data
"""
function f()
    # ...
end
```

Not OK:
```
"""
    f

Implement the f function on these data
"""

function f()
    # ...
end
```

This is the case for most docstrings in `/src`

**Comment by matbesancon** [comment]
Also, not that a block like:
```
"""
...
"""
```

does not define a comment but a string, it might create issues in your code

**Comment by kirui93** [comment]
Thank you for this. I was still wondering why the docstrings doesn't work but I think I have got a sufficient answer.

**Comment by matbesancon** [comment]
Linking to the review: https://github.com/openjournals/joss-reviews/issues/1912

**Comment by kirui93** [comment]
@matbesancon Thank you for this. I implemented everything concerning this and I am happy that it is now working, especially the docstrings.
