### ISSUE TITLE
[JOSS] Title and project setup

### ISSUE THREAD

**Issue by matbesancon** [kirui93/ScenTrees.jl#8]
The Project.toml doesn't seem to follow Pkg generated style, perform:
```julia
julia>]
(ScenTrees) pkg> instantiate
(ScenTrees) pkg> up
```
modifies the order of packages in Project.toml

The package itself should be referenced in the documentation's project, otherwise, when `activate`-ing the docs/Project.toml, there is no ScenTrees in the environment.

Following Julia's guidelines on package names, `ScenarioTrees.jl` might be a more explicit name compared to ScenTrees.jl, this is up to you and won't be a blocking issue for the JOSS review

**Comment by matbesancon** [comment]
Linking to the review: https://github.com/openjournals/joss-reviews/issues/1912

**Comment by kirui93** [comment]
We had a lot of options in terms of naming this package but we preferred `ScenTrees` as it is unique and it kind of explains more to what we are doing.
